### ISSUE TITLE
I think we're gonna share some issues.... Max-limit on input field

### ISSUE THREAD

**Issue by charlielafosse** [fac-15/KASH_todo#14]
As the title says, pretty much all the issues that our group are going to flag up for you guys will be the same for us!....

Functionality is great, and thanks for your pointers at the end of yesterday guys

Maybe put a max-limit for characters on your input field, and then run a test that expects an error message or similar when the user exceeds the limit. I copy and pasted a whole wikipedia page into your todo, for example

**Comment by aterna01** [comment]
Max length for user input is solved.
Thank you ))
We even didn't think about that....
