### ISSUE TITLE
Are you lot feeling ok?

### ISSUE THREAD

**Issue by VirtualDOMinic** [fac-15/KASH_todo#9]
https://github.com/fac-15/KASH_todo/blob/master/KASH-README.md 
:crying_cat_face:

**Comment by VirtualDOMinic** [comment]
Remember. Life is like TDD. All those "failures" are actually leading you to success :older_man: :older_woman: :key:

**Comment by tantsandras** [comment]
We are ok thanks :crying_cat_face: 
jkjk 

:rofl:
